server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_ordering
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

jwt:
  secret:
    access_token: "vpw8w3FcEWzlo0lUSHv4tocbybKbBTpS8t2dIk7amHmK49HJLXFL3aJS9J9WcYElGfXHrm5qBwJcpMtcQfZvHopct3Hr6ZkbKljh"
    refresh_token: "ijjywpQ8wc4sEtsc93yCE71hJiyApCdYYwTwJk0YkIekelvHGq4f3xe7egrLK4wzuJMbB3O9Fz1Ms3Eq5Pe1wQT4SZE934qjeqZu"
  expire:
    access_token: 1,
    refresh_token: 700

cloudinary:
  cloud-name:
  api-key:
  secret-key:
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode:
    secretKey:
    returnUrl: http://localhost:8080/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
client:
  domain: http://localhost:5173